### ISSUE TITLE
Contributor description on README

### ISSUE THREAD

**Issue by Shedrack-Sunday** [Shedrack-Sunday/Data-Structures-in-JavaScript#4]
On the README, a proper description and guide to contributing will be a proper addition to the project

**Comment by Vinitvh** [comment]
Hi @Shedrack-Sunday, can I work on this?

**Comment by Shedrack-Sunday** [comment]
> Hi @Shedrack-Sunday, can I work on this?

Hello @Vinitvh, sure can please
